# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c38e47145f0accbca0b6aa38629887d1df54a7957368e4f81d7f7dac6aafdb4cae709d003957abc098e4f587e8e329afdec363c58fe1bf44d38dd871a135b80

test:
  secret_key_base: 3a79f07f27f0f3e9a3eb201d9b70937b816384425ba13085af81aa81ce60588c7d089529ac3fe28700fbff441ec8437a3ae6c6bf322b9d5fc2ecf118510208bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
